spring:
  flyway:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:Fsa41306@127.0.0.1:3306/tcc?useTimezone=true&serverTimezone=UTC
    user: root
    password: Fsa41306
    schemas: tcc
#    baseline-on-migrate: true
