spring:
  flyway:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tccbd.mysql.database.azure.com:3306/tcc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    user: wendel
    password: Fsa41306
    schemas: tcc
#    baseline-on-migrate: true
