ALTER TABLE conta CHANGE COLUMN saldo saldo VARCHAR(30) NOT NULL;
ALTER TABLE despesas CHANGE COLUMN valor valor VARCHAR(30) NOT NULL;
ALTER TABLE rendas CHANGE COLUMN valor valor VARCHAR(30) NOT NULL;