ALTER TABLE rendas ADD INDEX FK_CONTA_RENDA_idx (origem ASC) VISIBLE;
ALTER TABLE rendas ADD CONSTRAINT FK_CONTA_RENDA FOREIGN KEY (origem) REFERENCES conta (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE despesas ADD INDEX FK_CONTA_DESPESAS_idx (origem ASC) VISIBLE;
ALTER TABLE despesas ADD CONSTRAINT FK_CONTA_DESPESAS FOREIGN KEY (origem) REFERENCES conta (id) ON DELETE NO ACTION ON UPDATE NO ACTION;



